[ui]
use_nerd_font_icons = true
ui_scale = 100  # tv UI to entire terminal
show_help_bar = true
input_bar_position = "bottom"

[previewers.file]
theme = "Catppuccin-mocha"  # list of available themes (tv shares syntax highlighting engine w/ bat) https://github.com/sharkdp/bat

[keybindings.Channel]
quit = "esc"
select_next_entry = "ctrl-n"  # previously 'down'
select_prev_entry = "ctrl-p"  # previously 'up'
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
select_entry = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"

[keybindings.RemoteControl]
quit = "esc"
select_next_entry = "down"
select_prev_entry = "up"
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_remote_control = "ctrl-r"
toggle_help = "ctrl-g"

[keybindings.SendToChannel]
quit = "esc"
select_next_entry = "down"
select_prev_entry = "up"
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"