command = /bin/zsh
click-repeat-interval = 500
auto-update-channel = stable
# keybind = cmd+r=reload_config  # doesn't seem to work

# VIZ
font-size = 18
theme = catppuccin-mocha
background-opacity = 0.9
# window-padding-x=10
# window-padding-y=10
window-decoration = true
window-save-state = always

# SPLITS
# adw-toolbar-style = raised
keybind = cmd+l=new_split:right
keybind = cmd+j=new_split:down
keybind = cmd+w=close_surface
