command = /bin/zsh
click-repeat-interval = 500
auto-update-channel = stable
# keybind = cmd+r=reload_config  # doesn't seem to work

# VIZ
font-size = 18
theme = catppuccin-mocha
background-opacity = 0.9
# window-padding-x=10
# window-padding-y=10
window-decoration = true
window-save-state = always
split-divider-color = #666666

# SPLITS
# adw-toolbar-style = raised
keybind = alt+l=new_split:right
keybind = alt+h=new_split:left
keybind = alt+j=new_split:down
keybind = alt+k=new_split:up
keybind = cmd+w=close_surface
keybind = cmd+h=goto_split:left
keybind = cmd+l=goto_split:right
keybind = cmd+j=goto_split:bottom
keybind = cmd+k=goto_split:top
