command = /bin/zsh
click-repeat-interval = 500
auto-update-channel = stable
# keybind = cmd+r=reload_config  # doesn't seem to work

# VIZ
font-size = 16
# theme = catppuccin-mocha
background-opacity = 0.9
# window-padding-x=10
# window-padding-y=10
window-decoration = true
window-save-state = always
split-divider-color = #666666
keybind = cmd+k=clear_screen

macos-option-as-alt = left
