[context]
sw = "/Users/zach/Documents/zv/notes/sw"
domains = "/Users/zach/Documents/zv/notes/domains"
bookcase ="/Users/zach/Documents/zv/notes/bookcase"
site = "/Users/zach/Documents/zv/projects/design/ux/myblog"

[rdd]
corkboard = "/Users/zach/Documents/zv/projects/tools/corkboard"
tasks = "/Users/zach/Documents/zv/personal/corkboard-tasks"
db = "/Users/zach/Documents/zv/projects/data/rdd"
emopic = "/Users/zach/Documents/zv/projects/ml/emopic"

[denv]
worklogs = "/Users/zach/Documents/zv/personal/worklogs"
dot = "/Users/zach/Documents/denv/dotfiles"
bin = "/Users/zach/Documents/denv/bin"
logs = "/Users/zach/Documents/denv/logs"

[colligo]
worklogs = "/Users/zach/Documents/zv/work/colligo/docs/worklogs"

[kero]
# agentic = "/Users/zach/Documents/zv/work/kero/docs/agentic"
# tickets = "/Users/zach/Documents/zv/work/kero/docs/tickets"
# worklogs = "/Users/zach/Documents/zv/work/kero/docs/worklogs"
# rush = "/Users/zach/Documents/zv/work/kero/src/automation/rush"
# eng = "/Users/zach/Documents/zv/work/kero/docs/eng"

[workflow]
# jina = "/Users/zach/Documents/zv/projects/design/architecture/jina"
# md-book = "/Users/zach/Documents/zv/projects/design/app/md-book"
# sympop = "/Users/zach/Documents/zv/projects/design/app/sympop"

[data]
# dataclerk = "/Users/zach/Documents/zv/projects/design/data/tooling/dataclerk"
# jmore = "/Users/zach/Documents/zv/projects/guts/jmore"
# wtfk = "/Users/zach/Documents/zv/projects/design/data/tooling/wtfk"
