PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE operations (id INTEGER PRIMARY KEY AUTOINCREMENT, data STRING);
CREATE TABLE sync_meta (key STRING PRIMARY KEY, value STRING);
CREATE TABLE tasks (uuid STRING PRIMARY KEY, data STRING);
CREATE TABLE working_set (id INTEGER PRIMARY KEY, uuid STRING);
DELETE FROM sqlite_sequence;
COMMIT;
