model = "gpt-5.5"
# model_reasoning_effort = "high"  # low, medium, high https://developers.openai.com/codex/concepts/subagents#reasoning-effort-model_reasoning_effort

[features]
codex_hooks = true

###
# PER-REPO PERMS
###

[projects."/Users/zach/Desktop"]
trust_level = "trusted"

[projects."/Users/zach/Documents/denv"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/notes/sw"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/materials/sw/lang/html-css/myblog"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/design/system/sgt"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/tools/gh-assess"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/personal/corkboard-tasks"]
trust_level = "trusted"

[projects."/Users/zach/Documents/denv/dotfiles"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/notes/bookcase"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/resume"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/design/system/rajant-odoo"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/tools/corkboard"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/design/ux/myblog"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/notes/domains"]
trust_level = "trusted"

[projects."/Users/zach/Documents/zv/projects/tools/resume"]
trust_level = "trusted"

[projects."/Users/zach/.codex"]
trust_level = "trusted"

